[tool.briefcase]
project_name = "wearable-collection"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/wearablecollection"
license = "BSD license"
author = 'Bronson Tharpe'
author_email = "btharpe2@student.gsu.edu"

[tool.briefcase.app.wearablecollection]
formal_name = "wearable-collection"
description = "Collect data from wearable devices."
icon = "src/wearablecollection/resources/wearablecollection"
sources = ['src/wearablecollection']
requires = []


[tool.briefcase.app.wearablecollection.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.wearablecollection.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.wearablecollection.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.wearablecollection.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.wearablecollection.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
